steps:
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/wil2023-408410/altrhoiapi01/demo01:latest', '.']
    dir: 'examples/api'
  - name: 'gcr.io/cloud-builders/docker:latest'
    args: ['push', 'europe-west1-docker.pkg.dev/wil2023-408410/altrhoiapi01/demo01:latest']
timeout: 3600s
options:
   logging: CLOUD_LOGGING_ONLY
